# Generated by Django 6.0.5 on 2026-05-13 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('assets', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='asset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='assetservice',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_services', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.category'),
        ),
        migrations.AddField(
            model_name='assetservice',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.document'),
        ),
        migrations.AddField(
            model_name='asset',
            name='documents',
            field=models.ManyToManyField(blank=True, to='assets.document'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.location'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Leave blank for global services usable by all departments', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
        migrations.AddField(
            model_name='assetservice',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.servicetype'),
        ),
    ]
