# Generated by Django 5.2.14 on 2026-05-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='model_number',
            new_name='model_detail',
        ),
        migrations.RenameField(
            model_name='assetassignment',
            old_name='asset',
            new_name='asset_id',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_cost',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='notes',
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='service_type',
            field=models.CharField(choices=[('NONE', 'None'), ('WARRANTY', 'Warranty'), ('INSURANCE', 'Insurance'), ('AMC', 'AMC')], default='NONE', max_length=20),
        ),
    ]
