# Generated by Django 5.2.14 on 2026-05-12 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_approval_status_asset_procurement_request_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='vendors.vendor'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
