# Generated by Django 6.0.5 on 2026-05-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_availability_assetservice_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
