# Generated by Django 6.0.5 on 2026-05-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('assets', '0004_alter_servicetype_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicetype',
            constraint=models.UniqueConstraint(fields=('name', 'department'), name='unique_service_type_per_department'),
        ),
    ]
