# Generated by Django 6.0.5 on 2026-05-14 08:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_servicetype_unique_service_type_per_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='approval_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
