from celery import shared_task
from celery.result import AsyncResult
from django.conf import settings
from django.utils import timezone
from datetime import timedelta

from .models import Report
from .services import generate_weekly_report
from .email_service import build_report_email
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.base import MIMEBase
from email import encoders


@shared_task(bind=True, max_retries=2)
def generate_report_task(self, user_id=None, report_id=None):
    from django.contrib.auth import get_user_model
    User = get_user_model()
    user = User.objects.get(id=user_id) if user_id else None

    try:
        existing = Report.objects.get(id=report_id) if report_id else None
        report = generate_weekly_report(user=user, report=existing)
        report.status = 'READY'
        report.task_id = self.request.id
        report.save(update_fields=['status', 'task_id'])
        send_report_to_admins_task.delay(report_id=report.id, triggered_by_user_id=user.id if user else None)
        return f"Report #{report.id} generated successfully"
    except Exception as exc:
        if report_id:
            Report.objects.filter(id=report_id).update(status='FAILED')
        raise self.retry(exc=exc, countdown=60)


@shared_task(max_retries=3)
def send_report_email_task(report_id):
    try:
        report = Report.objects.get(id=report_id)
    except Report.DoesNotExist:
        return "Report not found"

    if not settings.EMAIL_HOST_USER or not settings.REPORT_EMAIL_RECIPIENTS:
        return "Email not configured"

    msg = build_report_email(report)

    try:
        with smtplib.SMTP(settings.EMAIL_HOST, settings.EMAIL_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(settings.EMAIL_HOST_USER, settings.EMAIL_HOST_PASSWORD)
            server.send_message(msg)
        return f"Email sent for report #{report_id}"
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.error(f"Failed to send report email: {e}")
        raise


@shared_task
def send_report_to_admins_task(report_id, triggered_by_user_id=None):
    from django.contrib.auth import get_user_model
    User = get_user_model()
    from notifications.tasks import create_notification_task

    try:
        report = Report.objects.get(id=report_id)
    except Report.DoesNotExist:
        return "Report not found"

    admins = User.objects.filter(
        role__in=['SUPER_ADMIN', 'DEPARTMENT_ADMIN'],
        status='ACTIVE',
    ).exclude(email='')

    if not admins:
        return "No admin users found"

    sent_count = 0
    for admin in admins:
        create_notification_task.delay(
            user_id=admin.id,
            title="New Report Generated",
            message=f"A new inventory report '{report.title}' has been generated by {report.generated_by.username if report.generated_by else 'the system'}.",
        )

        try:
            msg = MIMEMultipart('mixed')
            msg['Subject'] = f"New Inventory Report: {report.title}"
            msg['From'] = settings.EMAIL_HOST_USER
            msg['To'] = admin.email

            base_url = settings.BASE_URL
            token = report.download_token

            alt = MIMEMultipart('alternative')
            html = f"""\
<html>
<body style="font-family:Helvetica,Arial,sans-serif;background:#0f172a;padding:24px;margin:0;">
<table cellpadding="0" cellspacing="0" style="max-width:600px;margin:0 auto;width:100%;">
<tr><td style="background:#1e293b;border-radius:12px;padding:24px;border:1px solid #334155;">
    <h1 style="color:#06b6d4;font-size:20px;margin:0 0 4px;">New Report Generated</h1>
    <p style="color:#64748b;font-size:12px;margin:0 0 16px;">
        Generated by {report.generated_by.username if report.generated_by else 'the system'}
    </p>
    <p style="color:#e2e8f0;font-size:14px;margin:0 0 16px;">
        <strong>{report.title}</strong>
    </p>
    <p style="color:#94a3b8;font-size:12px;margin:0 0 16px;">
        A new inventory report has been generated and is ready for review. The PDF report is attached to this email.
    </p>
    <table cellpadding="0" cellspacing="0" style="width:100%;margin-top:16px;padding-top:16px;border-top:1px solid #334155;">
        <tr><td style="text-align:center;">
            <a href="{base_url}/api/v1/reports/download/{token}/"
               style="display:inline-block;background:#ef4444;color:#fff;text-decoration:none;padding:8px 20px;border-radius:6px;font-size:12px;font-weight:600;margin:4px;">Download PDF</a>
            <a href="{base_url}/api/v1/reports/download-excel/{token}/"
               style="display:inline-block;background:#22c55e;color:#fff;text-decoration:none;padding:8px 20px;border-radius:6px;font-size:12px;font-weight:600;margin:4px;">Download Excel</a>
        </td></tr>
    </table>
</td></tr>
<tr><td style="text-align:center;padding-top:16px;">
    <p style="color:#334155;font-size:10px;">Inventory Management System</p>
</td></tr>
</table>
</body>
</html>"""

            alt.attach(MIMEText(html, 'html'))
            msg.attach(alt)

            if report.pdf_data:
                part = MIMEBase('application', 'pdf')
                payload = report.pdf_data.tobytes() if hasattr(report.pdf_data, 'tobytes') else bytes(report.pdf_data)
                part.set_payload(payload)
                encoders.encode_base64(part)
                part.add_header('Content-Disposition', 'attachment', filename=f"weekly_report_{report.created_at.strftime('%Y%m%d')}.pdf")
                msg.attach(part)

            with smtplib.SMTP(settings.EMAIL_HOST, settings.EMAIL_PORT) as server:
                server.ehlo()
                server.starttls()
                server.login(settings.EMAIL_HOST_USER, settings.EMAIL_HOST_PASSWORD)
                server.send_message(msg)
            sent_count += 1
        except Exception as e:
            import logging
            logger = logging.getLogger(__name__)
            logger.error(f"Failed to send report email to {admin.email}: {e}")

    return f"Notified {sent_count} admins about report #{report_id}"


@shared_task
def generate_and_email_report(user_id=None):
    result = generate_report_task.delay(user_id=user_id)
    return result.id


@shared_task
def clear_expired_charts():
    cutoff = timezone.now() - timedelta(hours=settings.CHART_EXPIRY_HOURS)
    qs = Report.objects.filter(
        created_at__lt=cutoff,
        chart_cleared=False,
        chart_data__isnull=False,
    )
    count = qs.count()
    for report in qs:
        report.clear_chart()
    return f"Cleared charts for {count} reports"


@shared_task
def delete_old_reports():
    cutoff = timezone.now() - timedelta(days=30 * settings.REPORT_RETENTION_MONTHS)
    qs = Report.objects.filter(created_at__lt=cutoff)
    count = qs.count()
    qs.delete()
    return f"Deleted {count} reports older than {settings.REPORT_RETENTION_MONTHS} months"


@shared_task
def generate_scheduled_weekly_report():
    result = generate_report_task.delay(user_id=None)
    return f"Scheduled report generation started (task {result.id})"
