# Generated by Django 5.2.14 on 2026-05-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('MANAGER', 'Manager'), ('USER', 'User')], default='EMPLOYEE', max_length=50),
        ),
    ]
