# Generated by Django 5.2.14 on 2026-05-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('MANAGER', 'Inventory Manager'), ('USER', 'User')], default='USER', max_length=50),
        ),
    ]
