# Generated by Django 6.0.5 on 2026-05-13 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('WEEKLY', 'Weekly Executive Report'), ('ASSET', 'Asset Report'), ('PROCUREMENT', 'Procurement Report'), ('REPAIR', 'Repair Report'), ('AUDIT', 'Audit Report')], max_length=50)),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='READY', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('download_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('pdf_data', models.BinaryField(blank=True, null=True)),
                ('excel_data', models.BinaryField(blank=True, null=True)),
                ('chart_data', models.BinaryField(blank=True, null=True)),
                ('chart_cleared', models.BooleanField(default=False)),
                ('summary_data', models.JSONField(blank=True, default=dict)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('task_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
