# Generated by Django 5.2.14 on 2026-05-13 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('WEEKLY', 'Weekly Executive Report'), ('ASSET', 'Asset Report'), ('PROCUREMENT', 'Procurement Report'), ('REPAIR', 'Repair Report'), ('AUDIT', 'Audit Report')], max_length=50)),
                ('pdf_data', models.BinaryField(blank=True, null=True)),
                ('excel_data', models.BinaryField(blank=True, null=True)),
                ('chart_data', models.BinaryField(blank=True, null=True)),
                ('chart_cleared', models.BooleanField(default=False)),
                ('summary_data', models.JSONField(blank=True, default=dict)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
