# Generated by Django 6.0.5 on 2026-05-14 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('notifications', '0002_notification_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ASSET_CREATED', 'Asset Created'), ('ASSET_APPROVED', 'Asset Approved'), ('ASSET_REJECTED', 'Asset Rejected'), ('PROCUREMENT_CREATED', 'Procurement Created'), ('PROCUREMENT_APPROVED', 'Procurement Approved'), ('PROCUREMENT_REJECTED', 'Procurement Rejected'), ('REPORT_GENERATED', 'Report Generated')], db_index=True, max_length=50)),
                ('email', models.BooleanField(default=False)),
                ('in_app', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['notification_type'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_f2e0f7_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'notification_type')},
        ),
    ]
